// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOUd3erFKuiILvfPXVOFzQnPrzfMzWKNk',
    appId: '1:815976563055:web:888742a7a8b9192c87a89a',
    messagingSenderId: '815976563055',
    projectId: 'flutter-firebase-bd798',
    authDomain: 'flutter-firebase-bd798.firebaseapp.com',
    storageBucket: 'flutter-firebase-bd798.firebasestorage.app',
    measurementId: 'G-59NS7V2HT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4F2aezmjCHlIXrlbiivb2p43UPh3yIAg',
    appId: '1:815976563055:android:81f1afc83d89575b87a89a',
    messagingSenderId: '815976563055',
    projectId: 'flutter-firebase-bd798',
    storageBucket: 'flutter-firebase-bd798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIzBxi8G2HCABgkqhzs9jMkp10y7k3jq8',
    appId: '1:815976563055:ios:aaaea5c166744aef87a89a',
    messagingSenderId: '815976563055',
    projectId: 'flutter-firebase-bd798',
    storageBucket: 'flutter-firebase-bd798.firebasestorage.app',
    iosBundleId: 'com.example.exempleFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIzBxi8G2HCABgkqhzs9jMkp10y7k3jq8',
    appId: '1:815976563055:ios:aaaea5c166744aef87a89a',
    messagingSenderId: '815976563055',
    projectId: 'flutter-firebase-bd798',
    storageBucket: 'flutter-firebase-bd798.firebasestorage.app',
    iosBundleId: 'com.example.exempleFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOUd3erFKuiILvfPXVOFzQnPrzfMzWKNk',
    appId: '1:815976563055:web:96d79b865d10031887a89a',
    messagingSenderId: '815976563055',
    projectId: 'flutter-firebase-bd798',
    authDomain: 'flutter-firebase-bd798.firebaseapp.com',
    storageBucket: 'flutter-firebase-bd798.firebasestorage.app',
    measurementId: 'G-RCECDDXJ3H',
  );
}
